project_name: mach-composer-plugin-sentry

env:
  - PRERELEASE={{ if index .Env "PRERELEASE"  }}{{ .Env.PRERELEASE }}{{ else }}false{{ end }}

builds:
  - id: "mach-composer-plugin"
    main: ./main.go
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

release:
  mode: replace
  prerelease: "{{ .Env.PRERELEASE }}"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - id: "mach-composer-plugin"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - LICENSE
