version: '3'

tasks:
  lint:
    cmd: golangci-lint run

  build:
    env:
      GORELEASER_CURRENT_TAG: v0.0.0
    cmd: goreleaser build --snapshot --single-target --clean

  test:
    cmd: go test -race ./...
